variable "subscription_id" {
  type        = "string"
  default     = "2bb0b94c-1af8-47c1-8464-e57c271869bb"
  description = "The Azure Subscription in which Resources should be deployed in."
}

variable "client_id" {
  type        = "string"
  description = "Service Principal ID"
}

variable "client_secret" {
  type        = "string"
  description = "Service Principal Secret/Passowrd"
}

variable "tenant_id" {
  type        = "string"
  default     = "3698556c-48eb-4511-8a0e-5fb6b7ebb01f"
  description = "Azure Tenant ID"
}

variable "product_key" {
  type        = "string"
  description = "The unique Product Key for your application. This will be used in the naming scheme of all resources created."
}

variable "application_name" {
  type        = "string"
  description = "The full name of your application. This is used in tagging your resources to allow for easy identification of your application resources."
}

variable "costcenter" {
  type        = "string"
  description = "The Cost Center that should be associated for resourcces created."
}

variable "deploy_scenario" {
  type        = "string"
  description = "The Deploy Scenario or Environment for your resources. This is used to make configuration decisions as well as naming of your resources."
}

variable "stack_aggregation" {
  type        = "string"
  description = "Stack Aggregation tagging is used to uniquely identify resources within the same deploy scenario. For example: blue, green, etc."
}

variable "environment" {
  type        = "string"
  description = "Describes the environment "
}

variable "region" {
  default     = "eastus2"
  description = "The Azure Location/Region your resources should be deployed in."
}

variable "created_by" {
  type        = "string"
  default     = "Terraform"
  description = "Describes who created these resources."
}

variable "sql_version" {
  type        = "string"
  description = "Version of SQL to use. Valid versions can be found at https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level?view=sql-server-2017"
}

variable "dwh_name" {
  type        = "string"
  description = "Name of the Data WareHouse. This will get appended to the Name generated by this Terraform run."
}

variable "dwh_admin" {
  type        = "string"
  description = "Describes administrator login name for the new server"
}

variable "dwh_pwd" {
  type        = "string"
  description = "Describes password associated with the dwh_admin user"
}

variable "sql_db_service_level" {
  type        = "string"
  description = "Describes which Performance Tier to use .It can be found at  https://azure.microsoft.com/en-us/pricing/details/sql-data-warehouse/gen2/ "
}
